import React, { useState, useEffect } from 'react';
import { useMatchday } from '../context/MatchdayContext';
import { Fixture, SuggestedSubPlan } from '../types';
import {
  Clock,
  ArrowRightLeft,
  X,
  Sliders,
  Check,
  Copy,
  Users,
  Shield,
  Sparkles,
  Timer,
  CheckCircle2,
  Calendar,
} from 'lucide-react';

interface SuggestedSubsModalProps {
  fixture: Fixture | null;
  isOpen: boolean;
  onClose: () => void;
}

export const SuggestedSubsModal: React.FC<SuggestedSubsModalProps> = ({
  fixture,
  isOpen,
  onClose,
}) => {
  const { getSuggestedSubs, settings } = useMatchday();

  const [interval, setInterval] = useState<number>(settings.defaultSubIntervalMinutes || 10);
  const [plans, setPlans] = useState<SuggestedSubPlan[]>([]);
  const [activePlanIndex, setActivePlanIndex] = useState<number>(0);
  const [loading, setLoading] = useState<boolean>(false);
  const [copied, setCopied] = useState<boolean>(false);

  const totalMatchMinutes =
    (settings.matchPeriodCount || 2) * (settings.periodDurationMinutes || 25);

  useEffect(() => {
    if (!isOpen || !fixture || !fixture.matchSquad) return;

    let isMounted = true;
    const fetchPlans = async () => {
      setLoading(true);
      try {
        const fetched = await getSuggestedSubs(fixture.id, interval);
        if (isMounted) {
          setPlans(fetched);
          setActivePlanIndex(0);
        }
      } catch (err) {
        console.error('Error fetching suggested subs:', err);
      } finally {
        if (isMounted) setLoading(false);
      }
    };

    fetchPlans();
    return () => {
      isMounted = false;
    };
  }, [fixture, interval, isOpen]);

  if (!isOpen || !fixture || !fixture.matchSquad) return null;

  const currentPlan = plans[activePlanIndex] || null;

  const handleCopyPlan = () => {
    if (!currentPlan) return;
    let text = `⏱ *SUBSHUFFLE SIDELINE SUB PLAN* vs ${fixture.opponent}\n`;
    text += `⏱ Strategy: ${currentPlan.strategyName}\n`;
    text += `⏱ Interval: Every ${interval} mins (${totalMatchMinutes}m match)\n\n`;

    currentPlan.windows.forEach((w) => {
      text += `*Minute ${w.minute}' (Period ${w.period}):*\n`;
      w.subChanges.forEach((ch) => {
        text += `  • 🔴 OFF: ${ch.offPlayerName} ➡️ 🟢 ON: ${ch.onPlayerName} (${ch.position})\n`;
      });
      text += '\n';
    });

    text += `_Generated by SubShuffle_`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const INTERVAL_PRESETS = [5, 8, 10, 12, 15];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fade-in">
      <div className="relative w-full max-w-3xl rounded-3xl bg-slate-900 border border-slate-800 shadow-2xl p-6 space-y-5 max-h-[90vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between pb-3 border-b border-slate-800 shrink-0">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-2xl bg-amber-500/10 text-amber-400 border border-amber-500/20">
              <ArrowRightLeft className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base font-bold text-white">Sideline Suggested Substitution Guide</h3>
                <span className="text-[10px] px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-300 border border-amber-500/20 font-semibold">
                  Live Match Assistant
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Automatic position-matched sideline rotation schedule vs {fixture.opponent} ({totalMatchMinutes} mins total)
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Configuration Bar */}
        <div className="p-4 rounded-2xl bg-slate-950/80 border border-slate-800 space-y-3 shrink-0">
          <div className="flex flex-wrap items-center justify-between gap-3 text-xs">
            <div className="flex items-center gap-2">
              <Timer className="w-4 h-4 text-sky-400" />
              <span className="font-semibold text-white">Rotation Interval:</span>
              <div className="flex items-center gap-1.5">
                {INTERVAL_PRESETS.map((intVal) => (
                  <button
                    key={intVal}
                    type="button"
                    onClick={() => setInterval(intVal)}
                    className={`px-2.5 py-1 rounded-lg font-bold text-xs transition cursor-pointer ${
                      interval === intVal
                        ? 'bg-sky-600 text-white shadow'
                        : 'bg-slate-900 text-slate-400 border border-slate-800 hover:text-white'
                    }`}
                  >
                    {intVal}m
                  </button>
                ))}
              </div>
            </div>

            <button
              type="button"
              onClick={handleCopyPlan}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-850 hover:bg-slate-800 text-slate-300 hover:text-white text-xs font-semibold border border-slate-700 transition cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied to Clipboard!' : 'Copy Sideline Plan'}</span>
            </button>
          </div>

          {/* Strategy Options Tabs */}
          {plans.length > 1 && (
            <div className="pt-2 border-t border-slate-800/80 flex items-center gap-2 overflow-x-auto text-xs">
              <span className="text-[11px] text-slate-500 font-semibold shrink-0">Options:</span>
              {plans.map((plan, idx) => (
                <button
                  key={plan.strategyName}
                  type="button"
                  onClick={() => setActivePlanIndex(idx)}
                  className={`px-3 py-1 rounded-lg font-semibold transition cursor-pointer shrink-0 ${
                    activePlanIndex === idx
                      ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40 shadow-sm'
                      : 'bg-slate-900 text-slate-400 border border-slate-800 hover:text-white'
                  }`}
                >
                  {plan.strategyName}
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Content Body: Timeline */}
        <div className="flex-1 overflow-y-auto space-y-4 pr-1 text-xs">
          {loading ? (
            <div className="p-12 text-center text-slate-400">
              Calculating position-matched substitutions...
            </div>
          ) : !currentPlan || currentPlan.windows.length === 0 ? (
            <div className="p-12 text-center rounded-2xl bg-slate-950/40 border border-slate-800 text-slate-400 space-y-2">
              <p>No in-period substitutions needed for this format or bench size.</p>
              <p className="text-[11px] text-slate-500">
                All players are already scheduled for fair rotation across halves!
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              <div className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 text-slate-300 text-xs">
                <p className="leading-relaxed">
                  <strong className="text-white">{currentPlan.strategyName}:</strong>{' '}
                  {currentPlan.strategyDescription}
                </p>
              </div>

              {/* Timeline Cards */}
              <div className="space-y-3 relative before:absolute before:inset-0 before:left-4 before:w-0.5 before:bg-slate-800">
                {currentPlan.windows.map((window, wIdx) => (
                  <div key={wIdx} className="relative pl-10">
                    {/* Minute Circle Pin */}
                    <div className="absolute left-1.5 top-3 -translate-x-1/2 w-6 h-6 rounded-full bg-slate-900 border-2 border-sky-500 text-sky-400 font-bold text-[10px] flex items-center justify-center shadow">
                      {window.minute}'
                    </div>

                    <div className="p-4 rounded-2xl bg-slate-950/80 border border-slate-800 space-y-3">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <span className="font-extrabold text-white text-sm">
                            Minute {window.minute}'
                          </span>
                          <span className="text-[10px] px-2 py-0.5 rounded-full bg-sky-500/10 text-sky-300 border border-sky-500/20 font-semibold">
                            Period {window.period}
                          </span>
                        </div>
                        <span className="text-[11px] text-slate-400">
                          {window.subChanges.length} substitution{window.subChanges.length > 1 ? 's' : ''}
                        </span>
                      </div>

                      {/* Sub Changes List */}
                      <div className="space-y-2">
                        {window.subChanges.map((change, cIdx) => (
                          <div
                            key={cIdx}
                            className="p-3 rounded-xl bg-slate-900 border border-slate-800/90 flex flex-wrap items-center justify-between gap-3"
                          >
                            <div className="flex items-center gap-3">
                              {/* Player Coming OFF */}
                              <div className="flex items-center gap-1.5">
                                <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-rose-500/20 text-rose-300 border border-rose-500/30">
                                  OFF
                                </span>
                                <span className="font-bold text-slate-200">
                                  {change.offPlayerName}
                                </span>
                              </div>

                              <ArrowRightLeft className="w-3.5 h-3.5 text-amber-400 shrink-0" />

                              {/* Player Coming ON */}
                              <div className="flex items-center gap-1.5">
                                <span className="text-[10px] font-bold px-1.5 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                                  ON
                                </span>
                                <span className="font-bold text-white">
                                  {change.onPlayerName}
                                </span>
                              </div>
                            </div>

                            <div className="flex items-center gap-2">
                              <span className="text-[11px] font-mono px-2 py-0.5 rounded bg-slate-950 border border-slate-800 text-sky-300">
                                {change.position}
                              </span>
                              {change.reason && (
                                <span className="text-[10px] text-slate-400 italic hidden sm:inline">
                                  {change.reason}
                                </span>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="pt-3 border-t border-slate-800 flex items-center justify-between text-xs">
          <span className="text-slate-400 text-[11px]">
            Sideline changes update fresh legs while maintaining equal playing time parity.
          </span>
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-sky-600 hover:bg-sky-500 text-white font-semibold transition cursor-pointer"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
};
